on:
  push:
    branches: [ main ]
    tags:
      - "v*.laser"
    paths:
      - boards/laser_f103ret7
      - applications/laser_ctrl
      - zephyr4_3.yml
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    name: Build zephyr image
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          path: workspace/apps

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.12

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          base-path: workspace
          app-path: apps
          toolchains: arm-zephyr-eabi
          manifest-file-name: zephyr4_3.yml

      - name: Build Firmware
        working-directory: workspace
        shell: bash
        run: |
          set -e
          west patch apply
          west build -b laser_f103ret7 apps/applications/laser_ctrl --sysbuild -Dlaser_ctrl_SNIPPET=imgmgr-shell
          west archive --no-rebuild --extra-file apps/docs/{刷机.docx,单点激光板测试.docx,固件升级.docx} -o laser_ctrl
          echo "IMAGE_ZIP=laser_ctrl.zip" >>  $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: laser_ctrl
          path: workspace/build/${{env.IMAGE_ZIP}}
          compression-level: 0

      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.4.2
        id: release
        with:
          files: workspace/build/${{env.IMAGE_ZIP}}

      - name: Send Email
        if: startsWith(github.ref, 'refs/tags/')
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Release zephyr APP ${{ github.ref_name }}
          body: |
            zephyr app Release: ${{ steps.release.outputs.url }}

            - Repository: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}

          to: ${{ secrets.TOLISTS }}
          from: GitHub Release
          attachments: workspace/build/${{env.IMAGE_ZIP}}
